version: otel_dataflow/v1
engine: {}
groups:
  default:
    pipelines:
      main:
        policies:
          channel_capacity:
              control:
                node: 100
                pipeline: 100
              pdata: 128

        nodes:
          receiver:
            type: receiver:otap
            config:
              listening_addr: "127.0.0.1:4318"
              response_stream_channel_size: 256
          perf:
            type: exporter:perf
            config:
              frequency: 5000
              cpu_usage: false
              mem_usage: false
              disk_usage: false
              io_usage: false

        connections:
          - from: receiver
            to: perf
