[package]
name = "otap-df-core-nodes"
description = "OTAP Core nodes"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-config = { path = "../config" }
otap-df-engine = { path = "../engine" }
otap-df-otap = { path = "../otap" }

async-trait.workspace = true
linkme.workspace = true
serde.workspace = true
serde_json.workspace = true